export type Classificacao = "Bug" | "Suporte" | "Integração" | "Customização" | "Melhoria"
export type Criticidade = "Alto" | "Intermediário" | "Baixo"
export type StatusChamado = "aberto" | "fechado" | "pendente"

export interface Chamado {
  id: number
  titulo: string
  responsavel: string
  cliente: string
  dataCriacao: string
  interacoes: number
  ultimaInteracao: string
  classificacao: Classificacao
  criticidade: Criticidade
  status: StatusChamado
}

export const statsData = {
  totalChamados: 11565,
  chamadosAbertos: 294,
  chamadosFechados: 11271,
  totalInteracoes: 48320,
}

export const ultimosChamados: Chamado[] = [
  {
    id: 151529,
    titulo: "PEDIDOS COM ESTRUTURA INCORRETA",
    responsavel: "Giovana Lana",
    cliente: "Teuto",
    dataCriacao: "12/02/2026 14:37",
    interacoes: 2,
    ultimaInteracao: "12/02/2026 15:43",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "aberto",
  },
  {
    id: 151528,
    titulo: "PEDIDO NAO SETORIZADO",
    responsavel: "Jéssica Rodrigues",
    cliente: "Teuto",
    dataCriacao: "12/02/2026 12:38",
    interacoes: 1,
    ultimaInteracao: "12/02/2026 12:40",
    classificacao: "Bug",
    criticidade: "Intermediário",
    status: "aberto",
  },
  {
    id: 151527,
    titulo: "Destaque na coluna tabela de preço",
    responsavel: "Jéssica Rodrigues",
    cliente: "Luchefarma",
    dataCriacao: "12/02/2026 11:52",
    interacoes: 1,
    ultimaInteracao: "12/02/2026 11:56",
    classificacao: "Customização",
    criticidade: "Baixo",
    status: "aberto",
  },
  {
    id: 151525,
    titulo: "REPLICAR PF PARA DF",
    responsavel: "Giovana Lana",
    cliente: "Sogamax",
    dataCriacao: "11/02/2026 17:40",
    interacoes: 2,
    ultimaInteracao: "12/02/2026 09:50",
    classificacao: "Suporte",
    criticidade: "Alto",
    status: "fechado",
  },
  {
    id: 151524,
    titulo: "Erro no Envio de Token",
    responsavel: "Igor Paulino",
    cliente: "Milfarma",
    dataCriacao: "11/02/2026 17:17",
    interacoes: 1,
    ultimaInteracao: "12/02/2026 13:31",
    classificacao: "Suporte",
    criticidade: "Intermediário",
    status: "fechado",
  },
  {
    id: 151523,
    titulo: "AJUSTE NA EXIBIÇÃO DE INFORMAÇÕES - AVISO DE DUPLICIDADE DE CNPJ",
    responsavel: "Jéssica Rodrigues",
    cliente: "Vitamedic",
    dataCriacao: "11/02/2026 16:47",
    interacoes: 1,
    ultimaInteracao: "11/02/2026 16:54",
    classificacao: "Melhoria",
    criticidade: "Baixo",
    status: "aberto",
  },
  {
    id: 151522,
    titulo: "AJUSTE CONFIGURAÇÃO TABELAS POR USUÁRIO",
    responsavel: "Jéssica Rodrigues",
    cliente: "Mais Saúde",
    dataCriacao: "11/02/2026 14:11",
    interacoes: 1,
    ultimaInteracao: "11/02/2026 16:05",
    classificacao: "Suporte",
    criticidade: "Intermediário",
    status: "aberto",
  },
  {
    id: 151521,
    titulo: "Erro ao Clonar Pedido",
    responsavel: "Igor Paulino",
    cliente: "Mais Saúde",
    dataCriacao: "11/02/2026 13:50",
    interacoes: 2,
    ultimaInteracao: "11/02/2026 14:41",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "aberto",
  },
  {
    id: 151520,
    titulo: "BI - Vendas por Equipe - Itens Foco",
    responsavel: "Jéssica Rodrigues",
    cliente: "Teuto",
    dataCriacao: "11/02/2026 13:16",
    interacoes: 1,
    ultimaInteracao: "11/02/2026 14:06",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "aberto",
  },
  {
    id: 151519,
    titulo: "Performance BI",
    responsavel: "Jéssica Rodrigues",
    cliente: "Teuto",
    dataCriacao: "11/02/2026 13:10",
    interacoes: 1,
    ultimaInteracao: "11/02/2026 14:05",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "aberto",
  },
]

export const chamadosPendentes: Chamado[] = []

export const chamadosFechados: Chamado[] = [
  {
    id: 151495,
    titulo: "Liberar acesso Helpdesk",
    responsavel: "Igor Paulino",
    cliente: "Teuto",
    dataCriacao: "06/02/2026 15:00",
    interacoes: 5,
    ultimaInteracao: "09/02/2026 14:40",
    classificacao: "Suporte",
    criticidade: "Baixo",
    status: "fechado",
  },
  {
    id: 151494,
    titulo: "Usuário Loja Sem Acesso ao Portal - Febrafar",
    responsavel: "Igor Paulino",
    cliente: "Foco PDV",
    dataCriacao: "06/02/2026 14:35",
    interacoes: 1,
    ultimaInteracao: "09/02/2026 14:26",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "fechado",
  },
  {
    id: 151491,
    titulo: "Corrigir status pedidos no Mapa",
    responsavel: "Jéssica Rodrigues",
    cliente: "Teuto",
    dataCriacao: "05/02/2026 14:38",
    interacoes: 8,
    ultimaInteracao: "09/02/2026 11:22",
    classificacao: "Suporte",
    criticidade: "Alto",
    status: "fechado",
  },
  {
    id: 151489,
    titulo: "Registro de solicitação de cancelamento de pedidos Merck",
    responsavel: "Edielma Silva",
    cliente: "Foco PDV",
    dataCriacao: "05/02/2026 12:02",
    interacoes: 2,
    ultimaInteracao: "05/02/2026 12:11",
    classificacao: "Integração",
    criticidade: "Baixo",
    status: "fechado",
  },
  {
    id: 151486,
    titulo: "Integração - Mixfarma Sergipe e Pernambuco",
    responsavel: "Ana Beatriz",
    cliente: "Globo Pharma",
    dataCriacao: "05/02/2026 09:12",
    interacoes: 4,
    ultimaInteracao: "05/02/2026 15:26",
    classificacao: "Integração",
    criticidade: "Baixo",
    status: "fechado",
  },
  {
    id: 151485,
    titulo: "Integrar arquivos Riosfarma e Plusfarma",
    responsavel: "Guilherme Borges",
    cliente: "Teuto",
    dataCriacao: "04/02/2026 17:11",
    interacoes: 3,
    ultimaInteracao: "04/02/2026 17:35",
    classificacao: "Integração",
    criticidade: "Intermediário",
    status: "fechado",
  },
  {
    id: 151474,
    titulo: "Mapa Analítico não exibe todas as vendas para Gerente Divisional",
    responsavel: "Igor Paulino",
    cliente: "Teuto",
    dataCriacao: "03/02/2026 14:23",
    interacoes: 4,
    ultimaInteracao: "09/02/2026 11:02",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "fechado",
  },
  {
    id: 151473,
    titulo: "Alterar status do pedido para Cancelado.",
    responsavel: "Ana Beatriz",
    cliente: "Teuto",
    dataCriacao: "03/02/2026 12:20",
    interacoes: 4,
    ultimaInteracao: "03/02/2026 14:36",
    classificacao: "Integração",
    criticidade: "Intermediário",
    status: "fechado",
  },
]
