import type { Chamado, ChamadoDetalhes, Interacao } from "./chamado/types"

export type { Chamado } from "./chamado/types"

export const statsData = {
  totalChamados: 11565,
  chamadosAbertos: 294,
  chamadosFechados: 11271,
  totalInteracoes: 48320,
}

export const allChamados: Chamado[] = [
  {
    id: 151529,
    titulo: "PEDIDOS COM ESTRUTURA INCORRETA",
    responsavel: "Giovana Lana",
    cliente: "Teuto",
    dataCriacao: "12/02/2026 14:37",
    interacoes: 4,
    ultimaInteracao: "12/02/2026 17:22",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "aberto",
    ferramenta: "PDV Link Plus",
    statusInterno: "Pendente análise",
  },
  {
    id: 151528,
    titulo: "PEDIDO NAO SETORIZADO",
    responsavel: "Jéssica Rodrigues",
    cliente: "Teuto",
    dataCriacao: "12/02/2026 12:38",
    interacoes: 1,
    ultimaInteracao: "12/02/2026 12:40",
    classificacao: "Bug",
    criticidade: "Intermediário",
    status: "aberto",
    ferramenta: "Foco PDV",
    statusInterno: "Em desenvolvimento",
  },
  {
    id: 151527,
    titulo: "Destaque na coluna tabela de preço",
    responsavel: "Jéssica Rodrigues",
    cliente: "Luchefarma",
    dataCriacao: "12/02/2026 11:52",
    interacoes: 1,
    ultimaInteracao: "12/02/2026 11:56",
    classificacao: "Customização",
    criticidade: "Baixo",
    status: "aberto",
    ferramenta: "PDV Link Plus",
    statusInterno: "Pendente análise",
  },
  {
    id: 151525,
    titulo: "REPLICAR PF PARA DF",
    responsavel: "Giovana Lana",
    cliente: "Sogamax",
    dataCriacao: "11/02/2026 17:40",
    interacoes: 2,
    ultimaInteracao: "12/02/2026 09:50",
    classificacao: "Suporte",
    criticidade: "Alto",
    status: "fechado",
    ferramenta: "Foco PDV",
    statusInterno: "Publicada",
  },
  {
    id: 151524,
    titulo: "Erro no Envio de Token",
    responsavel: "Igor Paulino",
    cliente: "Milfarma",
    dataCriacao: "11/02/2026 17:17",
    interacoes: 1,
    ultimaInteracao: "12/02/2026 13:31",
    classificacao: "Suporte",
    criticidade: "Intermediário",
    status: "fechado",
    ferramenta: "Foco PDV",
    statusInterno: "Publicada",
  },
  {
    id: 151523,
    titulo: "AJUSTE NA EXIBIÇÃO DE INFORMAÇÕES - AVISO DE DUPLICIDADE DE CNPJ",
    responsavel: "Jéssica Rodrigues",
    cliente: "Vitamedic",
    dataCriacao: "11/02/2026 16:47",
    interacoes: 1,
    ultimaInteracao: "11/02/2026 16:54",
    classificacao: "Melhoria",
    criticidade: "Baixo",
    status: "aberto",
    ferramenta: "PDV Link Plus",
    statusInterno: "Pendente análise",
  },
  {
    id: 151522,
    titulo: "AJUSTE CONFIGURAÇÃO TABELAS POR USUÁRIO",
    responsavel: "Jéssica Rodrigues",
    cliente: "Mais Saúde",
    dataCriacao: "11/02/2026 14:11",
    interacoes: 1,
    ultimaInteracao: "11/02/2026 16:05",
    classificacao: "Suporte",
    criticidade: "Intermediário",
    status: "aberto",
    ferramenta: "Foco PDV",
    statusInterno: "Em desenvolvimento",
  },
  {
    id: 151521,
    titulo: "Erro ao Clonar Pedido",
    responsavel: "Igor Paulino",
    cliente: "Mais Saúde",
    dataCriacao: "11/02/2026 13:50",
    interacoes: 2,
    ultimaInteracao: "11/02/2026 14:41",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "aberto",
    ferramenta: "PDV Link Plus",
    statusInterno: "Em desenvolvimento",
  },
  {
    id: 151520,
    titulo: "BI - Vendas por Equipe - Itens Foco",
    responsavel: "Jéssica Rodrigues",
    cliente: "Teuto",
    dataCriacao: "11/02/2026 13:16",
    interacoes: 1,
    ultimaInteracao: "11/02/2026 14:06",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "aberto",
    ferramenta: "Foco PDV",
    statusInterno: "Pendente análise",
  },
  {
    id: 151519,
    titulo: "Performance BI",
    responsavel: "Jéssica Rodrigues",
    cliente: "Teuto",
    dataCriacao: "11/02/2026 13:10",
    interacoes: 1,
    ultimaInteracao: "11/02/2026 14:05",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "aberto",
    ferramenta: "Foco PDV",
    statusInterno: "Pendente análise",
  },
  {
    id: 151495,
    titulo: "Liberar acesso Helpdesk",
    responsavel: "Igor Paulino",
    cliente: "Teuto",
    dataCriacao: "06/02/2026 15:00",
    interacoes: 5,
    ultimaInteracao: "09/02/2026 14:40",
    classificacao: "Suporte",
    criticidade: "Baixo",
    status: "fechado",
    ferramenta: "Foco PDV",
    statusInterno: "Publicada",
  },
  {
    id: 151494,
    titulo: "Usuário Loja Sem Acesso ao Portal - Febrafar",
    responsavel: "Igor Paulino",
    cliente: "Foco PDV",
    dataCriacao: "06/02/2026 14:35",
    interacoes: 1,
    ultimaInteracao: "09/02/2026 14:26",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "fechado",
    ferramenta: "Foco PDV",
    statusInterno: "Publicada",
  },
  {
    id: 151491,
    titulo: "Corrigir status pedidos no Mapa",
    responsavel: "Jéssica Rodrigues",
    cliente: "Teuto",
    dataCriacao: "05/02/2026 14:38",
    interacoes: 8,
    ultimaInteracao: "09/02/2026 11:22",
    classificacao: "Suporte",
    criticidade: "Alto",
    status: "fechado",
    ferramenta: "Foco PDV",
    statusInterno: "Publicada",
  },
  {
    id: 151489,
    titulo: "Registro de solicitação de cancelamento de pedidos Merck",
    responsavel: "Edielma Silva",
    cliente: "Foco PDV",
    dataCriacao: "05/02/2026 12:02",
    interacoes: 2,
    ultimaInteracao: "05/02/2026 12:11",
    classificacao: "Integração",
    criticidade: "Baixo",
    status: "fechado",
    ferramenta: "Foco PDV",
    statusInterno: "Publicada",
  },
  {
    id: 151486,
    titulo: "Integração - Mixfarma Sergipe e Pernambuco",
    responsavel: "Ana Beatriz",
    cliente: "Globo Pharma",
    dataCriacao: "05/02/2026 09:12",
    interacoes: 4,
    ultimaInteracao: "05/02/2026 15:26",
    classificacao: "Integração",
    criticidade: "Baixo",
    status: "fechado",
    ferramenta: "Foco PDV",
    statusInterno: "Publicada",
  },
  {
    id: 151485,
    titulo: "Integrar arquivos Riosfarma e Plusfarma",
    responsavel: "Guilherme Borges",
    cliente: "Teuto",
    dataCriacao: "04/02/2026 17:11",
    interacoes: 3,
    ultimaInteracao: "04/02/2026 17:35",
    classificacao: "Integração",
    criticidade: "Intermediário",
    status: "fechado",
    ferramenta: "Foco PDV",
    statusInterno: "Publicada",
  },
  {
    id: 151474,
    titulo: "Mapa Analítico não exibe todas as vendas para Gerente Divisional",
    responsavel: "Igor Paulino",
    cliente: "Teuto",
    dataCriacao: "03/02/2026 14:23",
    interacoes: 4,
    ultimaInteracao: "09/02/2026 11:02",
    classificacao: "Bug",
    criticidade: "Alto",
    status: "fechado",
    ferramenta: "Foco PDV",
    statusInterno: "Publicada",
  },
  {
    id: 151473,
    titulo: "Alterar status do pedido para Cancelado.",
    responsavel: "Ana Beatriz",
    cliente: "Teuto",
    dataCriacao: "03/02/2026 12:20",
    interacoes: 4,
    ultimaInteracao: "03/02/2026 14:36",
    classificacao: "Integração",
    criticidade: "Intermediário",
    status: "fechado",
    ferramenta: "Foco PDV",
    statusInterno: "Publicada",
  },
]

// Convenience sub-lists
export const ultimosChamados = allChamados.filter((c) => c.status === "aberto").slice(0, 10)
export const chamadosPendentes: Chamado[] = []
export const chamadosFechados = allChamados.filter((c) => c.status === "fechado")

// Mock interaction data for ticket 151529
const interacoes151529: Interacao[] = [
  {
    id: 1,
    idChamado: 151529,
    usuario: "Danillo Aurelio Cesario de Morais",
    data: "12/02/2026 14:37",
    tipo: "publica",
    mensagem:
      "Solicito a correção na estrutura dos pedidos no resumo anexo.\nCliente 89000. O cliente foi apropriado para o representante errado, diferente do que foi enviado pelo nosso sistema conforme evidencias em anexo.\n\nREPRESENTANTE NO RELATORIO: 7634 - VD COORD RJ 1 - SELL OUT SIM\nREPRESENTANTE CORRETO: 11294 - VD COORD RJ 2 - SELL OUT SIM",
    anexos: [
      { nome: "c_151529_PEDIDOS LUCMED FOCO.xlsb", url: "#", tipo: "xlsb" },
      { nome: "c_151529_PEDIDOS LUCMED CML.xlsb", url: "#", tipo: "xlsb" },
    ],
  },
  {
    id: 2,
    idChamado: 151529,
    usuario: "Giovana Lana",
    data: "12/02/2026 15:19",
    tipo: "publica",
    mensagem: "Boa tarde\n\nQual seria a local que precisa de correção por gentileza?\n\nFicamos a disposição. Att.",
  },
  {
    id: 3,
    idChamado: 151529,
    usuario: "Danillo Aurelio Cesario de Morais",
    data: "12/02/2026 15:43",
    tipo: "publica",
    mensagem:
      "Nas informações das colunas:\n\nCódigo Regional\nRegional\nCódigo Coordenação\nCoordenação\nCódigo Setor\nSetor Venda\nCódigo Representante\nRepresentante",
  },
  {
    id: 4,
    idChamado: 151529,
    usuario: "Giovana Lana",
    data: "12/02/2026 17:22",
    tipo: "interna",
    mensagem: "Estamos averiguando com o cliente via whatsapp e com o Du via teams.",
    destinatarios: ["Jéssica Rodrigues"],
  },
]

// Build detail lookup
const detalhesMap: Record<number, ChamadoDetalhes> = {}

allChamados.forEach((c) => {
  detalhesMap[c.id] = {
    ...c,
    solicitante: c.cliente,
    historicoInteracoes:
      c.id === 151529
        ? interacoes151529
        : [
            {
              id: 1,
              idChamado: c.id,
              usuario: c.responsavel,
              data: c.dataCriacao,
              tipo: "publica" as const,
              mensagem: `Chamado #${c.id} - ${c.titulo}. Interação inicial registrada.`,
            },
          ],
  }
})

export function getChamadoById(id: number): ChamadoDetalhes | undefined {
  return detalhesMap[id]
}

export function getChamados(): Chamado[] {
  return allChamados
}
